# Generated by Django 6.0.5 on 2026-06-13 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recommender', '0002_alter_prediction_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='Phone_Number',
            new_name='Phone',
        ),
    ]
